import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/templates/Sidebar/Sidebar";

const poppins = Poppins({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  variable: '--font-poppins',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <section className="h-screen w-full main-page">
          <div className="sidebar-style hidden lg:flex">
            <Sidebar />
          </div>
          <div className="bg-white dark:bg-gray-800 container">
            {children}
          </div>
        </section>
      </body>
    </html>
  );
}
