import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/templates/Sidebar/Sidebar";
import Header from "@/components/templates/Header/Header";

const poppins = Poppins({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  variable: '--font-poppins',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} dark`}>
        <section className="min-h-dvh w-full main-page bg-gray-900">
          <div className="sidebar-style hidden lg:flex">
            <Sidebar />
          </div>
          <div className="bg-white main dark:bg-gray-900 relative">
            <div className="absolute pattern inset-0"></div>
            <div className="container z-10 relative">
              <Header />
              {children}
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
